test certs - cherry-pick PR325 on v2
grpc-ecosystem/go-grpc-middleware pull request #331
Opened 2020-09-08 12:47 UTC by dmitris

PR copies the changes in #325 onto the v2 branch. See issue #324 for background.

2020-09-08 13:01 UTC, johanbrandhorst approved these changes

2020-09-09 09:05 UTC, johanbrandhorst requested changes
Wait a sec, shouldn't this be deleting the existing certs too?

2020-09-09 09:24 UTC, dmitris commented
> Wait a sec, shouldn't this be deleting the existing certs too?

done in 1b508da

2020-09-09 09:26 UTC, johanbrandhorst commented on grpctesting/interceptor_suite.go
> +			CommonName: "Certify Test Cert",
Ah, doh, we should probably change this too :sweat_smile:

2020-09-09 09:41 UTC, johanbrandhorst approved these changes

2020-09-09 09:54 UTC, merged

2020-09-09 09:54 UTC, johanbrandhorst commented
Thanks for your contribution!