Add skip interceptor
grpc-ecosystem/go-grpc-middleware pull request #364
Opened 2020-11-24 11:27 UTC by XSAM

Resolve #363 

It's hard to transfer a `interceptors.UnaryServerInterceptor` into `interceptors.Reporter`, so I use the old way to implement this feature.

2020-11-24 13:30 UTC, bwplotka approved these changes
Nice, I like it, but curious why denylist was chosen instead of allowlist approach? :thinking: 

To me allowlist approach might be more comprehensive. E.g If you want to use logging middleware only on service X. I will add `SKIP -> Logging, filter service != x` Doable but quite big inversion (: 

I think we could consider this, at the end it's flexible enough anyway, just curious what is easier to use.

Skip might be nice for auth aspect, so by default you deny from auth etc.. Maybe does not matter that much :hugs: 

LGTM, overall :muscle:

2020-11-24 13:30 UTC, bwplotka commented on interceptors/skip/examples_test.go
> +func ReflectionFilter(ctx context.Context, gRPCType interceptors.GRPCType, service string, method string) bool {
```suggestion
func SkilReflectionService(ctx context.Context, gRPCType interceptors.GRPCType, service string, method string) bool {
```

2020-11-24 13:30 UTC, bwplotka commented on interceptors/skip/examples_test.go
> +func exampleAuthFunc(ctx context.Context) (context.Context, error) {
```suggestion
func dummyAuth(ctx context.Context) (context.Context, error) {
```

2020-11-24 13:30 UTC, bwplotka commented on interceptors/skip/examples_test.go
> +func exampleAuthFunc(ctx context.Context) (context.Context, error) {
It's function so no need for `Func` suffix (:

2020-11-24 13:30 UTC, bwplotka commented on interceptors/skip/interceptor.go
> +type Filter func(ctx context.Context, gRPCType interceptors.GRPCType, service string, method string) bool
```suggestion
type Filter func(ctx context.Context, typ interceptors.GRPCType, svc string, method string) bool
```

2020-11-24 13:30 UTC, bwplotka commented on interceptors/skip/interceptor.go
> +type Filter func(ctx context.Context, gRPCType interceptors.GRPCType, service string, method string) bool
let's make it conceise

2020-11-24 13:30 UTC, bwplotka commented on interceptors/skip/interceptor.go
> +			// Skip interceptor
```suggestion
			// Skip interceptor.
```

2020-11-24 13:30 UTC, bwplotka commented on interceptors/skip/interceptor.go
> +			// Skip interceptor
```suggestion
			// Skip interceptor.
```

2020-11-25 02:01 UTC, XSAM commented
> To me allowlist approach might be more comprehensive.

I agree with that. At the first design, `If service == x then skip` seems good, but the function is called `filter`. Therefore, `filter service != x` seems better.

2020-12-02 12:45 UTC, XSAM commented
@johanbrandhorst Shall we merge it?

2020-12-02 14:20 UTC, johanbrandhorst requested changes
LGTM, but could we add this new interceptor to the README too please? Sorry for the delayed review.

2020-12-05 04:06 UTC, XSAM commented
@googlebot I consent.

2020-12-05 04:09 UTC, XSAM commented
@johanbrandhorst It seems like the CLA bot is not working.

2020-12-05 14:18 UTC, johanbrandhorst commented
I think @bwplotka might need to consent too.

2020-12-05 14:19 UTC, johanbrandhorst approved these changes

2020-12-11 04:58 UTC, XSAM commented
@bwplotka Shall we?

2020-12-30 16:15 UTC, yashrsharma44 commented
Yeah, seems like @bwplotka also need to consent 😛

2020-12-30 16:36 UTC, bwplotka approved these changes
Sorry for lag, if you think it makes sense I am happy as well. LGTM!

2020-12-30 16:36 UTC, bwplotka commented
@googlebot I consent.

2020-12-30 16:37 UTC, bwplotka commented
All is good to me, so merging.

2020-12-30 16:37 UTC, merged