docs: add `logging.InjectFields` usage description
grpc-ecosystem/go-grpc-middleware pull request #541
Opened 2023-03-08 11:22 UTC by aimuz

Fixed #521

2023-03-09 05:26 UTC, johanbrandhorst reviewed
I'm confused by this change. Did we remove the `tags` interceptor? If so, we should just remove it from the list, not keep it strikethrough.

2023-03-09 08:51 UTC, aimuz commented
The implementation of tags has been removed in v2.

2023-03-09 21:59 UTC, johanbrandhorst requested changes
Thanks for the clarification, lets just remove this.

2023-03-09 21:59 UTC, johanbrandhorst commented on README.md
> +   * ~~[`tags`](interceptors/tags) - a library that adds a `Tag` map to context, with data populated from request body.~~ replace `tags.Extract().Set()` to `logging.InjectFields()`
Lets just remove this line

2023-03-10 17:41 UTC, johanbrandhorst approved these changes

2023-03-10 17:42 UTC, merged

2023-03-10 17:42 UTC, johanbrandhorst commented
Thanks for your contribution!