Support for subsystem in grpc prometheus counter and histogram metrics
grpc-ecosystem/go-grpc-middleware pull request #639
Opened 2023-09-15 09:53 UTC by rohsaini

## Changes

Introduction of apis: WithSubsystem() and WithHistogramSubsystem()

## Verification

Tested locally with this new package of go-grpc-middleware

2023-09-15 17:40 UTC, johanbrandhorst requested changes
Can you add some tests that exercises this option and checks that the output contains the subsystem?

2023-09-15 17:40 UTC, johanbrandhorst commented on providers/prometheus/options.go
> +// WithSubsystem allows you to add Subsytem to Counter metrics.
```suggestion
// WithSubsystem allows you to add a Subsystem to Counter metrics.
```

2023-09-15 17:40 UTC, johanbrandhorst commented on providers/prometheus/options.go
> +// WithHistogramSubsystem allows you to add Subsytem to histograms metrics.
```suggestion
// WithHistogramSubsystem allows you to add a Subsystem to histograms metrics.
```

2023-09-18 07:45 UTC, rohsaini commented on providers/prometheus/options.go
> +// WithSubsystem allows you to add Subsytem to Counter metrics.
done

2023-09-18 07:45 UTC, rohsaini commented on providers/prometheus/options.go
> +// WithHistogramSubsystem allows you to add Subsytem to histograms metrics.
done.

2023-09-18 07:47 UTC, rohsaini commented
> Can you add some tests that exercises this option and checks that the output contains the subsystem?

added new test cases for client and server metrics both.

cd /home/ubuntu/datadisk/CLONES/go-grpc-middleware-subsystem/providers/prometheus && go test -v -race ./...
=== RUN   TestClientInterceptorSuite
=== RUN   TestClientInterceptorSuite/TestStartedStreamingIncrementsStarted
=== RUN   TestClientInterceptorSuite/TestStreamingIncrementsMetrics
=== RUN   TestClientInterceptorSuite/TestUnaryIncrementsMetrics
=== RUN   TestClientInterceptorSuite/TestWithSubsystem
=== NAME  TestClientInterceptorSuite
    interceptor_suite.go:154: stopped grpc.Server at: 127.0.0.1:40133
--- PASS: TestClientInterceptorSuite (0.24s)
    --- PASS: TestClientInterceptorSuite/TestStartedStreamingIncrementsStarted (0.00s)
    --- PASS: TestClientInterceptorSuite/TestStreamingIncrementsMetrics (0.01s)
    --- PASS: TestClientInterceptorSuite/TestUnaryIncrementsMetrics (0.00s)
    --- PASS: TestClientInterceptorSuite/TestWithSubsystem (0.00s) **<<<<<<<<**
=== RUN   TestServerInterceptorSuite
=== RUN   TestServerInterceptorSuite/TestContextCancelledTreatedAsStatus
=== RUN   TestServerInterceptorSuite/TestRegisterPresetsStuff
=== RUN   TestServerInterceptorSuite/TestStartedStreamingIncrementsStarted
=== RUN   TestServerInterceptorSuite/TestStreamingIncrementsMetrics
=== RUN   TestServerInterceptorSuite/TestUnaryIncrementsMetrics
=== RUN   TestServerInterceptorSuite/TestWithSubsystem
=== NAME  TestServerInterceptorSuite
    interceptor_suite.go:154: stopped grpc.Server at: 127.0.0.1:38755
--- PASS: TestServerInterceptorSuite (0.73s)
    --- PASS: TestServerInterceptorSuite/TestContextCancelledTreatedAsStatus (0.10s)
    --- PASS: TestServerInterceptorSuite/TestRegisterPresetsStuff (0.03s)
    --- PASS: TestServerInterceptorSuite/TestStartedStreamingIncrementsStarted (0.20s)
    --- PASS: TestServerInterceptorSuite/TestStreamingIncrementsMetrics (0.11s)
    --- PASS: TestServerInterceptorSuite/TestUnaryIncrementsMetrics (0.00s)
    --- PASS: TestServerInterceptorSuite/TestWithSubsystem (0.00s) **<<<<<<<<**
PASS
ok  	github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus	1.006s

2023-09-18 08:09 UTC, rohsaini commented
Will raise it again. Closing due to some CLA issues.

2023-09-18 08:09 UTC, closed without merging