Support retriable func condition
grpc-ecosystem/go-grpc-middleware pull request #687
Opened 2024-01-12 09:13 UTC by tamayika

Closes #686

## Changes

Add retry condition on arbitratry error.
This option overcedes WithCodes and default retriable logic.

## Verification

Test code added.

2024-01-19 23:10 UTC, ggilmore commented
This is a drive-by comment, but I think your approach would be better if you:

1. Have your `type RetriableFunc func(err error) bool` be the only option to be able to accept / reject errors (e.g. get rid of the status codes slice) from the retry `options` struct. 


Ex:

```diff
type options struct {
	max             uint
	perCallTimeout  time.Duration
	includeHeader   bool
-	codes           []codes.Code
	backoffFunc     BackoffFunc
	onRetryCallback OnRetryCallback
+	retriableFunc   RetriableFunc
}

```

2. Refactor the `WithCodes` options func as a `retriableFunc`:

```go
// WithCodes sets which codes should be retried.
//
// Please *use with care*, as you may be retrying non-idempotent calls.
//
// You cannot automatically retry on Cancelled and Deadline, please use `WithPerRetryTimeout` for these.
func WithCodes(retryCodes ...codes.Code) CallOption {
	return CallOption{applyFunc: func(o *options) {
                o.retriableFunc = func(err error) bool {
                     c := status.Code(err)

                     for _, code := retryCodes {
                        if c == code {
                           return true 
                        }
                     }
                     
                     return false
                 }
	}}
}
```

This maintains backwards compatibility with the existing of the library that are using `WithCodes`, and gives a library a deeper interface (fewer APIs needed to achieve the same functionality).

2024-01-24 00:55 UTC, johanbrandhorst requested changes
Hi, thanks for your PR! This is nice, but I also agree with @ggilmore that we could simplify the internal logic to use the new function. Mind making the changes suggested?

2024-01-28 08:42 UTC, tamayika commented
@johanbrandhorst @ggilmore 
thanks, I refactored WithCodes option.

2024-01-29 19:03 UTC, johanbrandhorst approved these changes
LGTM

2024-01-29 19:03 UTC, merged

2024-01-29 19:03 UTC, johanbrandhorst commented
Thanks for your contribution!