Fix grpc middleware interceptor not PostCall-ing when a streaming RPC with non-streaming server finishes successfully.
grpc-ecosystem/go-grpc-middleware pull request #725
Opened 2024-09-28 12:37 UTC by alexandrupitis1

Current Client-side Stream Interceptor implementation is bugged - it assumes that if the RPC is streaming, then the Server must be streaming responses too. This is incorrect, as a Streaming RPC can be either a Bidi stream ( which are currently handled properly ), or a Client-side only stream. In this case, if the RPC finished successfully, then PostCall never fires as Interceptor assumes it should get an io.EOF ( which obviously does not make sense when Server is not sending a response stream ).

This most obviously manifests when using it with Prometheus reporter - client side metrics for such RPCs that depend on PostCall ( grpc_client_handled_total, grpc_client_handling_seconds ) are not exported.

## Changes

- Client StreamInterceptor now handles cases when Server is streaming or non-streaming separately.

## Verification

- I created a POC with a Client-streaming, Server non-streaming RPC and modified the example in this repo to run it. Verified that the example does not export certain prometheus metrics ( grpc_client_handled_total, grpc_client_handling_seconds ) for said RPC.
- Applied the fix, verified again that the metrics are now exported

.

2024-10-03 03:30 UTC, johanbrandhorst requested changes
Nice! Could you add a test for this?

2024-10-27 23:52 UTC, alexandrupitis1 commented
@johanbrandhorst OK i finally had some time to take another pass at this. I added a test and a relevant API to the testpb proto. I had to update grpc-go though - is it OK or should I make an effort to make sure I re-gen the testpb grpc using the same versions you have in repo?

2024-10-28 02:00 UTC, johanbrandhorst requested changes

2024-10-28 10:08 UTC, alexandrupitis1 commented on testing/testpb/v1/test.proto
> +  rpc PingStreamSingleResponse(stream PingStreamRequest) returns (PingStreamResponse) {}
Done

2024-10-30 23:52 UTC, alexandrupitis1 commented
I ran make lint and cleared out all linting issues, but the github check is failing:

>> lint proto files
>> ensuring copyright headers
cannot set copyright headers: you have unstaged changes.
M	README.md

Not exactly sure what to make of it. Do I need to modify something else?

2024-10-31 01:05 UTC, johanbrandhorst commented
I think the README thing is a bug, I'm not sure why it happens but I won't let it block this merge

2024-10-31 01:05 UTC, johanbrandhorst approved these changes

2024-10-31 01:05 UTC, merged

2024-10-31 01:06 UTC, johanbrandhorst commented
Thank you for your contribution!